development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: gatling
  username: thegoat
  password: massakaffe
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: gatling
  username: thegoat
  password: massakaffe
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000
